name: Scan Repo
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
      - '.installer/**'
      - 'apps/**'
      - 'preinstall/**'
      - 'traefik/**'
      - 'scripts/**'
      - 'wiki/**'

jobs:
  screpo:
    name: Scan Repository

    permissions:
      contents: read
      security-events: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          token: ${{ secrets.CR_PAT }}
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@ee6a4f5af1dbe22ccc11905a61abd2db301d532c
        with:
          scan-type: 'fs'
          ignore-unfixed: 'true'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
