name: upstream

on:
  schedule:
    - cron: '* 1 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - uses: actions/checkout@v4.1.6
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        with:
          COMMIT_MSG: '#fix'
          MAX_LINES: 10
